### ISSUE TITLE
npm version is not updated

### ISSUE THREAD

**Issue by serglider** [pixijs/pixi-animate#58]
Hello guys,

Thanks for the great piece of software. I tried to npm install the latest version with https://github.com/jiborobot/pixi-animate/issues/48 resolved (https://github.com/jiborobot/pixi-animate/blob/0ee40bcd08b332d97829a8555bdc086f875f24c5/src/animate/SymbolLoader.js#L15)  Unfortunately this fix is not in the latest version

**Comment by stevenalanstark** [comment]
you can always just install by the github URL and branch, see: [https://docs.npmjs.com/cli/install](https://docs.npmjs.com/cli/install)

**Comment by ericente** [comment]
NPM version is now updated!
