### ISSUE TITLE
Action in frame0 only execute once

### ISSUE THREAD

**Issue by k8w** [pixijs/pixi-animate#67]
[Demo fla here](https://k8w.github.io/pixi-animate-frame0-script-issue/test123.fla) 

**Reproduce**
1. Create a MovieClip with 3 frame
1. Each frame have its frame script ( `console.log(frameNumber)` )
1. Run, and you would see the first frame number is only print one time. (Infers that script in frame 0 only execute 1 time)

[Online demo](https://k8w.github.io/pixi-animate-frame0-script-issue/)
See the console
**Expect**
```
1
2
3
1
2
3
...
```
**Actual**
```
1
2
3
2
3
2
3
...
```

**Comment by k8w** [comment]
I have made a PR for this: https://github.com/jiborobot/pixi-animate/pull/68

**Comment by k8w** [comment]
PR: https://github.com/jiborobot/pixi-animate/pull/70

**Comment by ericente** [comment]
Your fix is in the latest release, 1.3.4. Thank you!
