### ISSUE TITLE
Requires PIXI error

### ISSUE THREAD

**Issue by bdanis** [pixijs/pixi-animate#93]
is V5 supported? getting a pixi linkage issue
Typescript project setup
importing like this on the main script file

import 'pixi.js';
import 'pixi-animate';

**Comment by bigtimebuddy** [comment]
v5 is not fully supported yet. The pixi.js package no long creates the global PIXI object (which pixi-animate requires). If you’re using webpack you can define the external global as a workaround: https://webpack.js.org/configuration/externals/
