### ISSUE TITLE
Adobe Animate 2020 API changes

### ISSUE THREAD

**Issue by bigtimebuddy** [pixijs/pixi-animate#97]
I received this email from Adobe about changes in 2020. We will need to fix this.

————-

Dear CPSDK Plugin Developers - Greetings from Animate Team!

We have released Animate 2020 couple of days back and this release has an updated CPSDK and Sample Plugin. 

In addition we would like to inform you about the change that requires your attention as your plugin may not show up in Animate 2020

Background:

Animate 2019 and older versions of Animate uses Xerces lib version 3.1 which has been updated to Xerces lib 3.2 in Animate 2020. The older CPSDK Sample plugin has a dependency on Xerces lib version 3.1 installed with Animate and the plugins built based on older sample plugin will not find Xerces 3.1 in Animate 2020 and hence will not load. 

Solution:

You can just comment out the following piece of code to remove the Xerces library dependency in your plugin

In DocType.cpp remove/comment following lines

#include "MyXmlParser.h"

#include "xercesc/framework/MemBufInputSource.hpp"

try {

            XMLPlatformUtils::Initialize();

            FeatureDocumentHandler featureXmlDocHandler(this);

            SAXParser *parser = new SAXParser();

            parser->setDocumentHandler(&featureXmlDocHandler);
            XERCES_CPP_NAMESPACE::MemBufInputSource    *memInput = new XERCES_CPP_NAMESPACE::MemBufInputSource((const XMLByte*) buffer, length, "dummy", false);

            m_bInited = true;

            parser->parse(*memInput);

            delete parser;

            delete memInput;

            XMLPlatformUtils::Terminate();

        }

        catch (...) {

            ASSERT(0);

        }

Delete/Remove MyXmlParser.cpp from project
Remove Xerces libs from project settings
You can refer to the latest CPSDK Sample Plugin where the Xerces lib dependency has been removed.

Or remove the dependency of the Xerces lib installed by Animate and package a version of Xerces lib that you are using if needed for any reason in the plugin itself.

Please let us know if you need any more details.

Thanks!

Mohan

**Comment by Nordikum** [comment]
PixiAnimate Extension how to install for Adobe Animate 2020?
(PixiAnimate extension version 1.4.0)
I am not able to install Pixi-Animate extension on my Adobe Animate 2020.
Anastasiy Extension Manager not working with Adobe Animate 2020.
Can you please share guidelines on how to install it.

Thank you in advance.

**Comment by bigtimebuddy** [comment]
Does not support Animate 2020 because API changes mentioned in the issue above.  If someone would like to make and test changes, would welcome contributions.

**Comment by andrewstart** [comment]
This was fixed in v1.4.1 of pixi-animate-extension.
